# Generated by Django 5.1.2 on 2024-10-15 20:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Closed', 'Closed')], max_length=10)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='MetricCategory',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('weight', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('category_type', models.CharField(choices=[('KPI', 'Key Performance Indicator'), ('COMP', 'Competency')], max_length=4)),
            ],
            options={
                'verbose_name': 'Metric Category',
                'verbose_name_plural': 'Metric Categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('full_name', models.CharField(max_length=500)),
                ('hr_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('level', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade', models.CharField(max_length=2)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.employee')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.evaluation')),
            ],
            options={
                'verbose_name': 'Employee Evaluation',
                'verbose_name_plural': 'Employee Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_approval', models.BooleanField(default=False)),
                ('hr_approval', models.BooleanField(default=False)),
                ('employee_approval', models.BooleanField(default=False)),
                ('manager_comments', models.TextField(blank=True)),
                ('hr_comments', models.TextField(blank=True)),
                ('employee_comments', models.TextField(blank=True)),
                ('employee_evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pms.employeeevaluation')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMetricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('employee_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.employeeevaluation')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.metric')),
            ],
            options={
                'verbose_name': 'Employee Metric Score',
                'verbose_name_plural': 'Employee Metric Scores',
            },
        ),
        migrations.AddField(
            model_name='metric',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.metriccategory'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.section'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('employee_level', models.CharField(max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.template'),
        ),
        migrations.AddField(
            model_name='metric',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.template'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.template'),
        ),
    ]
