# Generated by Django 5.1 on 2024-10-15 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('full_name', models.CharField(max_length=500)),
                ('hr_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_year', models.PositiveSmallIntegerField()),
                ('evaluation_date', models.DurationField()),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Closed', 'Closed')], max_length=10)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=250)),
                ('metric_weight', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
        migrations.CreateModel(
            name='MetricCategory',
            fields=[
                ('category_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category_Weight', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'metric_category',
                'verbose_name_plural': 'metric_categories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departmetns',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.PositiveSmallIntegerField()),
                ('evaluation_grade', models.CharField(max_length=2)),
                ('employe_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.employee')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.evaluation')),
            ],
            options={
                'verbose_name': 'EmployeeEvaluation',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_approval', models.BooleanField(default=False)),
                ('hr_approval', models.BooleanField(default=False)),
                ('employee_approval', models.BooleanField(default=False)),
                ('employee_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.employeeevaluation')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
            },
        ),
        migrations.CreateModel(
            name='EmployeeMetricScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_score', models.PositiveSmallIntegerField()),
                ('employee_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.employee')),
                ('metric_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.metric')),
            ],
            options={
                'verbose_name': 'EmployeeMericScore',
            },
        ),
        migrations.AddField(
            model_name='metric',
            name='metric_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.metriccategory'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.department')),
                ('section_maanger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.template'),
        ),
        migrations.AddField(
            model_name='metric',
            name='template_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pms.template'),
        ),
    ]
