# Generated by Django 5.1.2 on 2024-10-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0002_alter_metric_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='level',
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.ManyToManyField(to='pms.level'),
        ),
    ]
