# Generated by Django 5.1.2 on 2024-10-28 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0003_remove_employee_level_employee_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='level',
        ),
        migrations.AddField(
            model_name='employee',
            name='level',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='pms.level'),
            preserve_default=False,
        ),
    ]
