# Generated by Django 5.1.2 on 2024-11-02 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0005_evaluation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pms.level'),
            preserve_default=False,
        ),
    ]
