# Generated by Django 5.1.2 on 2024-11-10 09:47

import pms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0007_evaluation_evaluator_alter_evaluation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[pms.models.score_validator]),
        ),
    ]
