# Generated by Django 5.1.2 on 2024-11-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0011_finalscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalscore',
            name='score',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B+', 'B+'), ('B', 'B'), ('C', 'C')], max_length=2),
        ),
    ]
